about/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.about_us, name='about'),
]

home/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.ArticleList.as_view(), name='home'),
    path('<slug:slug>/', views.detail, name='detail'),
    path('<slug:slug>/edit_review/<int:review_id>', views.review_edit, name='review_edit'),  # noqa
    path('<slug:slug>/review_delete/<int:review_id>', views.review_delete, name='review_delete'),  # noqa
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("about/", include("about.urls"), name="about-urls"),
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls'), name='home-urls'),
]

about/models.py
from django.db import models


# Create your models here.

class About(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title

home/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
import cloudinary
import cloudinary.uploader
import cloudinary.api

# Create your models here.

CATEGORY_CHOICES = (0, "Beach"), (1, "History"), (2, "City")
STATUS = (0, "Draft"), (1, "Published")
RATE = (0, "★ - Change the rating (Currently one star is chosen)"), (1, "★★"), (2, "★★★"), (3, "★★★★"), (4, "★★★★★")  # noqa


class Article(models.Model):
    title = models.CharField(max_length=30, unique=True)
    slug = models.SlugField(max_length=30, unique=True)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=0)
    description = models.TextField(null=True)
    content = models.TextField()
    article_image = CloudinaryField('cover image', default='placeholder')
    detail_image = CloudinaryField('detail image', default='placeholder')
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return f'Article Name: {self.title}'


class Reviews(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='chosen_article')  # noqa
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commenter')  # noqa
    review_title = models.CharField(max_length=20)
    rate = models.IntegerField(choices=RATE, default=0)
    comment_area = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    post_image = CloudinaryField('Post image', blank=True, null=True)

    class Meta:
        ordering = ['-comment_date']

    def __str__(self):
        return f'Comment for : {self.article}'

home/forms.py
from .models import Reviews
from .models import Reviews as Reviews, Article
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['review_title', 'rate', 'comment_area']

about/views.py
from django.shortcuts import render
from .models import About

# Create your views here.


def about_us(request):
    """
    Renders the About page
    """
    about = About.objects.all().first()

    return render(
        request,
        "about/about.html",
        {"about": about},
    )

home/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Article, Reviews
from .forms import ReviewForm

# import cloudinary.uploader

# Create your views here.


class ArticleList(generic.ListView):
    queryset = Article.objects.all().order_by("title").values()
    template_name = "home/index.html"
    paginate_by = 4


def detail(request, slug):
    """
    Display an individual article
    """
    queryset = Article.objects.all()
    detail = get_object_or_404(queryset, slug=slug)
    reviews = detail.chosen_article.all().order_by("-comment_date")
    reviews_count = detail.chosen_article.count()
    # Write Review Submission
    if request.method == "POST":
        review_form = ReviewForm(data=request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.author = request.user
            review.article = detail
            review.save()
            messages.add_message(
                request, messages.SUCCESS, "Comment submitted Thank you!!"
            )

    review_form = ReviewForm()

    return render(
        request,
        "home/detail.html",
        {
            "article": detail,
            "reviews": reviews,
            "reviews_count": reviews_count,
            "review_form": review_form,
        },
    )


def review_edit(request, slug, review_id):
    """
    view to edit review
    """
    if request.method == "POST":

        queryset = Article.objects.filter(status=1)
        article = get_object_or_404(queryset, slug=slug)
        review = get_object_or_404(Reviews, pk=review_id)
        review_form = ReviewForm(data=request.POST, instance=review)

        if review_form.is_valid() and review.author == request.user:
            review = review_form.save(commit=False)
            review.post = Reviews
            review.approverd = False
            review.save()
            messages.add_message(request, messages.SUCCESS, "Comment Updated!")
        else:
            messages.add_message(request, messages.ERROR, "Error Comment Updating")  # noqa

        return HttpResponseRedirect(reverse("detail", args=[slug]))


def review_delete(request, slug, review_id):
    """
    view to delete review
    """
    queryset = Article.objects.filter(status=1)
    article = get_object_or_404(queryset, slug=slug)
    review = get_object_or_404(Reviews, pk=review_id)

    if review.author == request.user:
        review.delete()
        messages.add_message(request, messages.SUCCESS, "Review deleted!")
    else:
        messages.add_message(request, messages.ERROR, "Not Success!")

    return HttpResponseRedirect(reverse("detail", args=[slug]))

about/templates/about/about.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- About Us Top Image -->
<div class="aboutus-img"></div>
<!--About page content-->
<section class="aboutus-content">
   <h1 class="aboutus-title">About Us</h1>
   <h2 class="about-title">{{ about.title }}</h2>
   {{ about.content | linebreaks }}
</section>
{% endblock content %}

home/templates/home/detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% load crispy_forms_tags %}
<main id="detail">
   <!--The content of the articles that the user clicked.-->
   <section class="detail-section">
      <div class="container detail-top">
         <div class="row">
            <div class="col-12 col-lg-6">
               <img class="img-fluid" src="{{article.detail_image.url}}" alt="Article image">
            </div>
            <div class="col-12 col-lg-6 article-content">
               <div>
                  <h2 class="article-title">{{article.title}}</h2>
                  {{article.content | linebreaks}}
               </div>
            </div>
         </div>
      </div>
   </section>
   <!--Review sevtion-->
   <section class="review-section">
      <h2 class="review-title">Explore Reviews</h2>
      <!-- Write Review button -->
      {% if user.is_authenticated %}
      <div class="review-btns">
         <div class="write-review-btn1">
            <a class="nav-link write-review" href="#add-review-section">Write Review</a>
         </div>
      </div>
      {% else %}
         <p class="message-review">If you wish to share your holiday experience, please log In first.</p>
      {% endif %}
      <!-- Review -->
      {% if reviews %}
      <div class="comment-count">
         <i class="fa-regular fa-message"> {{reviews_count}} </i>
      </div>
      {% for review in reviews %}
      <div class="container review-container">
         <div class="row review-img-container">
            <div class="col-12 col-sm-4 col-lg-3 review-img-div">
               <img class="img-fluid review-img" src="{{article.detail_image.url}}" alt="Article image">
            </div>
            <div class="col-12 col-sm-8 col-lg-9 review-details">
               <h4 id="review{{review.id}}_title" class="review-title1">{{review.review_title}}</h4>
               <p id="review{{review.id}}_rating" class="hide">{{review.rate}}</p>
               {% if review.rate == 0 %}
               <p>★</p>
               {% elif review.rate == 1 %}
               <p>★</p>
               {% elif review.rate == 2 %}
               <p>★★</p>
               {% elif review.rate == 3 %}
               <p>★★★</p>
               {% elif review.rate == 4 %}
               <p>★★★★</p>
               {% endif %}
               <div id="review{{review.id}}">{{review.comment_area|linebreaks }}</div>
               <p>{{review.comment_date}}</p>
               <!-- Edit button -->
               {% if user.is_authenticated and review.author == user %}
               <div class="edit-delete-btns">
                  <button class="btn btn-sm edit-btn" data-review_id="{{ review.id }}">Edit</button>
                  <button class="btn btn-sm btn-delete" data-review_id="{{ review.id }}">Delete</button>
               </div>
               {% endif %}
            </div>
         </div>
      </div>
      {% endfor %}
      {% else %}
      <p class="no-review">No reviews have been posted yet</p>
      {% endif %}
      <!-- Delete confirmation modal -->
      <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
         <div class="modal-dialog">
            <div class="modal-content">
               <div class="modal-header">
                  <h5 class="modal-title" id="deleteModalLabel">Delete comment?</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body">
                  Are you sure you want to delete your comment?
                  This action cannot be undone.
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <a id="deleteConfirm" href="#" class="btn
                     btn-danger">Delete</a>
               </div>
            </div>
         </div>
      </div>
      {% if reviews_count >= 1%}
      <div class="d-flex justify-content-center go-top-1">
         <a class=" go-top btn-sm" href="#detail">Back To Top</a>
      </div>
      {% endif %}
   </section>
   <!--Form Section-->
   {% if user.is_authenticated %}
   <section id="add-review-section" class="container-fluid form-hide">
      <!-- Form -->
      <div class="review-form">
         <h2 class="review-title">Review Form</h2>
         <p class="review-lead-message">Let's share your holiday experience !! To share your experience, please fill out
            this form down below.</p>
         <form id="reviewForm" method="post">
            <p>Review as : {{ user.username }}</p>
            <div>
               <p>Write a review for : {{article.title}}</p>
            </div>
            <div>
               {{ review_form | crispy }}
               {% csrf_token %}
            </div>
            <button id="submitBtn" type="submit" class="submit-btn btn btn-primary">Submit</button>
            <a class="go-top btn-sm" href="{% url 'detail' article.slug %}">Quit</a>
         </form>
      </div>
      <div class="d-flex justify-content-center go-top-2 ">
         <a class="go-top btn-sm" href="#detail">Back To Top</a>
      </div>
   </section>
   {% endif %}
</main>
{% endblock content %}
{% block extras %}
<script src="{% static 'js/review.js' %}"></script>
{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}
{% block content %}
{% load static%}
<main>
   <!--Hero image, Lead message, Login and ragister-->
   <section id="hero-img">
      <div class="lead-message-container">
         <div class="lead-message-inner-container">
            <h2 class="lead-message">Travel Reviews</h2>
            <p class="lead-message">Share Your Holiday Experience</p>
            <div class="d-grid gap-2 d-sm-flex justify-content-sm-center lead-btns">
               {% if user.is_authenticated %}
               <a class="lead-logout-btn nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page" href="{% url 'account_logout' %}">Logout</a>
               {% else %}
               <a class="lead-register-btn nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page"
                  href="{% url 'account_signup' %}">Register</a>
               <a class="lead-login-btn nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page" href="{% url 'account_login' %}">Login</a>
               {% endif %}
            </div>
            {% if user.is_authenticated %}
            <p class='logged-in-user'>Logged in as {{ user }}</p>
            {% endif %}
         </div>
      </div>
   </section>
   <!--Articles-->
   <section id="articles">
      <h3 class="text-center">Holiday Reviews</h3>
      <div class="col-12 mt-3 justify-content-center justify-content-lg-start">
         <div class="row justify-content-center justify-content-lg-center">
            {%for article in article_list %}
            {% if article.status == 1 %}
            <div class="card md-4 m-4 cover" style="width: 18rem;">
               {% if 'placeholder' in article.article_image.url %}
               <img class="card-img-top" src="{% static 'images/default.webp'%}" alt="Card image">
               {% else %}
               <img class="card-img-top" src="{{ article.article_image.url}}" alt="Card image">
               {% endif %}
               <div class="card-body container text-center">
                  {% if article.category == 0%}
                  <p class="category-tag beach">Beach</p>
                  {% elif article.category == 1 %}
                  <p class="category-tag history">History</p>
                  {% else %}
                  <p class="category-tag city">City</p>
                  {% endif %}
                  <p class="card-title">{{article.title}}</p>
                  <p class="card-text text-start">{{article.description}}</p>
                  <a href="{% url 'detail' article.slug %}" class="btn btn-explore btn-primary">Explore</a>
               </div>
            </div>
            <br>
            {% endif %} 
            {% endfor%}
         </div>
      </div>
      <!--Pagenation-->
      {% if is_paginated %}
      <nav aria-label="Page navigation">
         <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li >
               <a href="?page={{ page_obj.previous_page_number }}"
                  class="page-link next">&laquo; PREV</a>
            </li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link next"> NEXT &raquo;</a></li>
            {% endif %}
         </ul>
      </nav>
      {% endif %}
   </section>
</main>
{% endblock %}

templates/base.html
{% load static %}
{% url 'home' as home_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}
{% url 'about' as about_url %}
<!Doctype html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Meta for search engine -->
      <meta name="description"
         content="Explore and share the travel review with Rate Your Stay. You will find information about holiday information all over the world. Also, you can share your holiday experience with others.">
      <meta name="keyword"
         content="Travel, Travel Review, Review, Holiday, Experience, Beach, City, Historic Site">
      <!-- Title -->
      <title>RATE YOUR STAY</title>
      <!-- Font Awesome CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
      <!--Google Fonts-->
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css2?family=Cinzel&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
         integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
      <!-- Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <!-- fontawesomefree -->
      <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
      <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
      <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
      <!-- Favicon -->  
      <link rel="icon" type="image/ico" href="{% static 'favicon/favicon.ico'%}">
      <!-- Solves mixed content warning -->
      <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
   </head>
   <body>
      <header>
         <!--Navigation bar-->
         <nav class="navbar navbar-expand-lg navbar-dark nav-colour" style="background:#222831 ;">
            <div class="container-fluid">
               <h1 class="title"><a class="navbar-brand" href="{% url 'home'%}"  aria-label="Late your stay logo links to Home page">RATE YOUR STAY</a></h1>
               <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
               <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                  <ul class="navbar-nav">
                     <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home'%}" aria-label="Link to Home page">Home</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{%url 'about'%}" aria-label="Link to About us page">About Us</a>
                     </li>
                     {% if user.is_authenticated %}
                     <li class="nav-item">
                        <a class="nav-link {% if request.path == logout_url %}active{% endif %}" aria-current="page" href="{% url 'account_logout' %}" aria-label="Link to Logout Page">Logout</a>
                     </li>
                     {% else %}
                     <li class="nav-item">
                        <a class="nav-link {% if request.path == signup_url %}active{% endif %}" aria-current="page"
                           href="{% url 'account_signup' %}" aria-label="Link to Register page">Register</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link {% if request.path == login_url %}active{% endif %}" aria-current="page" href="{% url 'account_login' %}" aria-label="Link to Login page">Login</a>
                     </li>
                     {% endif %}
                  </ul>
               </div>
            </div>
         </nav>
         <!-- displaying Django messages -->
         <div class="container-fluid conf-box">
            <div class=" conf-message">
               {% for message in messages %}
               <div class="alert {{ message.tags }} alert-dismissible
                  fade show" id="msg" role="alert">
                  {{ message | safe }}
                  <button type="button" class="btn-close bg-white"
                     data-bs-dismiss="alert" aria-label="Close"></button>
               </div>
               {% endfor %}
            </div>
         </div>
      </header>
      {% block content %}
      <!-- Review Contenting -->
      {% endblock content %}
      <!-- Help Center Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-hidden="true">
         <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
               <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Help Center</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
               </div>
               <div class="modal-body text-center">
                  <p>If you have any issue please don't hesitate to contact us</p>
                  <p>Email: rate-your-self@supportdesk.com</p>
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" aria-label="A button to close help-center">Close</button>
               </div>
            </div>
         </div>
      </div>
      <footer>
         <div class="social-media">       
            <a href="https://www.facebook.com/" aria-label="Visit our Facebook page (opens in a new tub)" target="_blank"><i class="fa-brands fa-facebook-f fa-xl" style="color: #ffffff;"></i></a>
            <a href="https://www.instagram.com/" aria-label="Visit our Instagram page (opens in a new tub)" target="_blank"><i class="fa-brands fa-instagram fa-xl" style="color: #ffffff;"></i></a>
            <a href="https://www.youtube.com/" aria-label="Visit our YouTube page (opens in a new tub)" target="_blank"><i class="fa-brands fa-youtube fa-xl" style="color: #ffffff;"></i></a>
         </div>
         <div class="nav-item help-center">
            <!-- Helpcenter button -->
            <button class="help-center btn" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Help Center
            </button>
         </div>
      </footer>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
      {% block extras %}
      {% endblock %}
   </body>
</html>

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <section class="totp">
        <h2>{% translate "Authenticator App" %}</h2>
        {% if authenticators.totp %}
            <p>{% translate "Authentication using an authenticator app is active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_deactivate_totp' %}">{% translate "Deactivate" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "An authenticator app is not active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_activate_totp' %}">{% translate "Activate" %}</a>
                </li>
            </ul>
        {% endif %}
    </section>
    <section class="recovery_codes">
        <h2>{% translate "Recovery Codes" %}</h2>
        {% if authenticators.recovery_codes %}
            <p>
                {% blocktranslate with total_count=authenticators.recovery_codes.generate_codes|length count unused_count=authenticators.recovery_codes.get_unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
            </p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_view_recovery_codes' %}">{% translate "View codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "No recovery codes set up." %}</p>
        {% endif %}
    </section>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    </p>
    {% if unused_codes %}
        <textarea class="recovery-codes" rows="{{ unused_codes|length }}" readonly>{% for code in unused_codes %}{{ code }}
{% endfor %}
</textarea>
    {% endif %}
    <ul class="actions">
        {% if unused_codes %}
            <li>
                <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
            </li>
        {% endif %}
        <li>
            <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
        </li>
    </ul>
{% endblock content %}

templates/mfa/totp/activate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Activate Authenticator App" %}</h1>
    {{ totp_svg|safe }}
    <form method="POST" action="{% url 'mfa_activate_totp' %}">
        {% csrf_token %}
        <p>
            <label>{% translate "Authenticator secret" %}:</label>
            <input type="text"
                   disabled="disabled"
                   value="{{ form.secret }}"
                   size="{{ form.secret|length }}">
        </p>
        {{ form.as_p }}
        <button type="submit">{% trans "Activate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/mfa/totp/deactivate_form.html
{% extends "mfa/totp/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Deactivate Authenticator App" %}</h1>
    <p>
        {% blocktranslate %}You are about to deactivate authenticator app based authentication. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_deactivate_totp' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Deactivate" %}</button>
    </form>
{% endblock content %}